// Lottery contract configuration
// UPDATE THESE VALUES with your deployed contract addresses on Sepolia

export const LOTTERY_CONTRACT_ADDRESS = "0x27Cac012848e79feB8d74F6A9028A3f0CA5F4211"; // TODO: Replace with deployed Lottery address
export const OM_TOKEN_ADDRESS = "0xFEC00AD65dCCf090319d79Ef80c7DaaF065C5Da1"; // TODO: Replace with deployed OmToken address

export const SEPOLIA_CHAIN_ID = 11155111;

export const LOTTERY_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_minimumEntryTickets", type: "uint256", internalType: "uint256"           },
      { name: "_interval",            type: "uint256", internalType: "uint256"           },
      { name: "_vrfCoordinator",      type: "address", internalType: "address"           },
      { name: "_keyHash",             type: "bytes32", internalType: "bytes32"           },
      { name: "_subId",               type: "uint256", internalType: "uint256"           },
      { name: "_callbackGasLimit",    type: "uint32",  internalType: "uint32"            },
      { name: "_tokenContract",       type: "address", internalType: "contract OmToken"  },
    ],
    stateMutability: "nonpayable",
  },

  { type: "receive", stateMutability: "payable" },

  {
    type: "function",
    name: "enterIntoGame",
    inputs:  [{ name: "tickets", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "takeTokensFromEth",
    inputs:  [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "blockAddress",
    inputs:  [{ name: "player", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unblockAddress",
    inputs:  [{ name: "player", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addressBlockStatus",
    inputs:  [{ name: "player", type: "address", internalType: "address" }],
    outputs: [{ name: "",       type: "bool",    internalType: "bool"    }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockedAddresses",
    inputs:  [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOwner",
    inputs:  [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInterval",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLastTimeStamp",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLotteryState",
    inputs:  [],
    outputs: [{ name: "", type: "uint8", internalType: "enum Lottery.LotteryState" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMinimumTicketsRequired",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenPriceInWei",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFeeWalletAddress",
    inputs:  [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPrizePool",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllCurrentPlayersWithAmount",
    inputs:  [],
    outputs: [
      { name: "", type: "address[]", internalType: "address[]" },
      { name: "", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerByIndex",
    inputs:  [{ name: "idx", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "",    type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewAllWinners",
    inputs:  [],
    outputs: [{ name: "", type: "address[2][]", internalType: "address[2][]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_totalTicketsSold",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_allWinners",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_vrfCoordinator",
    inputs:  [],
    outputs: [{ name: "", type: "address", internalType: "contract IVRFCoordinatorV2Plus" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs:  [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnerShip",
    inputs:  [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs:  [{ name: "to", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs:  [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeInterval",
    inputs:  [{ name: "_interval",        type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeMinimumEntryTickets",
    inputs:  [{ name: "newMinimum",       type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeTokenPrice",
    inputs:  [{ name: "newTokenPrice",    type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeFeeWalletAddress",
    inputs:  [{ name: "feeWalletAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeState",
    inputs:  [{ name: "_newState", type: "uint8", internalType: "enum Lottery.LotteryState" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCoordinator",
    inputs:  [{ name: "_vrfCoordinator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resetLottery",
    inputs:  [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "restartTimer",
    inputs:  [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawAllFunds",
    inputs:  [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "checkUpkeep",
    inputs:  [{ name: "data", type: "bytes", internalType: "bytes" }],
    outputs: [
      { name: "upkeepNeeded", type: "bool",  internalType: "bool"  },
      { name: "performData",  type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "performUpkeep",
    inputs:  [{ name: "performData", type: "bytes", internalType: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rawFulfillRandomWords",
    inputs: [
      { name: "requestId",   type: "uint256",   internalType: "uint256"   },
      { name: "randomWords", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "playerEnterIntoGame",
    inputs: [
      { name: "player", type: "address", indexed: true,  internalType: "address" },
      { name: "tokens", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "purchaseTokens",
    inputs: [
      { name: "player", type: "address", indexed: true,  internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "winnersAreDeclared",
    inputs: [
      { name: "winner1", type: "address", indexed: true, internalType: "address" },
      { name: "winner2", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestIdGenerated",
    inputs: [
      { name: "reqId", type: "uint256", indexed: true, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SecondWinnerSentFailed",
    inputs: [
      { name: "secondWinner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CoordinatorSet",
    inputs: [
      { name: "vrfCoordinator", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferRequested",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to",   type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to",   type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AddressAlreadyBlocked",           inputs: [{ name: "player",           type: "address", internalType: "address" }] },
  { type: "error", name: "AddressNotAlreadyBlocked",        inputs: [{ name: "player",           type: "address", internalType: "address" }] },
  { type: "error", name: "AddressWasBlocked",               inputs: [{ name: "player",           type: "address", internalType: "address" }] },
  { type: "error", name: "onlyOwnerIsAllowed",              inputs: [{ name: "player",           type: "address", internalType: "address" }] },
  { type: "error", name: "TicketNotExists",                 inputs: [{ name: "ticketNumber",     type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "NotEnoughTicketsToEnterIntoGame", inputs: [{ name: "tickets",          type: "uint256", internalType: "uint256" }, { name: "minimumRequired",  type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "NotMultipleOfTokenPrice",         inputs: [{ name: "userEnteredValue", type: "uint256", internalType: "uint256" }, { name: "singleTokenPrice", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "UpKeepCheckFailed",               inputs: [{ name: "players",          type: "uint256", internalType: "uint256" }, { name: "balance",          type: "uint256", internalType: "uint256" }, { name: "timePassed",  type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "OnlyCoordinatorCanFulfill",       inputs: [{ name: "have",             type: "address", internalType: "address" }, { name: "want",             type: "address", internalType: "address" }] },
  { type: "error", name: "OnlyOwnerOrCoordinator",          inputs: [{ name: "have",             type: "address", internalType: "address" }, { name: "owner",            type: "address", internalType: "address" }, { name: "coordinator", type: "address", internalType: "address" }] },
  { type: "error", name: "LotteryIsBlocked",                inputs: [] },
  { type: "error", name: "LotteryIsNotOpen",                inputs: [] },
  { type: "error", name: "NotEnoughBalance",                inputs: [] },
  { type: "error", name: "ResetLotteryFailed",              inputs: [] },
  { type: "error", name: "WithdrawFailed",                  inputs: [] },
  { type: "error", name: "Winner_Transaction_Failed",       inputs: [] },
  { type: "error", name: "ZeroAddress",                     inputs: [] },
] as const;


export const OM_TOKEN_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "initialSupply", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs:  [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs:  [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs:  [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs:  [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs:  [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "",        type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner",   type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to",    type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "value",   type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from",  type: "address", internalType: "address" },
      { name: "to",    type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "burn",
    inputs:  [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to",     type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLotteryContract",
    inputs:  [{ name: "lotteryAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getLotteryContract",
    inputs:  [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_owner",
    inputs:  [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from",  type: "address", indexed: true,  internalType: "address" },
      { name: "to",    type: "address", indexed: true,  internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { name: "owner",   type: "address", indexed: true,  internalType: "address" },
      { name: "spender", type: "address", indexed: true,  internalType: "address" },
      { name: "value",   type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "NotValidLotteryContract",  inputs: [{ name: "lottery",  type: "address", internalType: "address" }] },
  { type: "error", name: "AlreadyLotteryAddressSet", inputs: [{ name: "lottery",  type: "address", internalType: "address" }] },
  { type: "error", name: "onlyOwnerIsAllowed",       inputs: [{ name: "sender",   type: "address", internalType: "address" }] },
  { type: "error", name: "ERC20InvalidSender",       inputs: [{ name: "sender",   type: "address", internalType: "address" }] },
  { type: "error", name: "ERC20InvalidReceiver",     inputs: [{ name: "receiver", type: "address", internalType: "address" }] },
  { type: "error", name: "ERC20InvalidSpender",      inputs: [{ name: "spender",  type: "address", internalType: "address" }] },
  { type: "error", name: "ERC20InvalidApprover",     inputs: [{ name: "approver", type: "address", internalType: "address" }] },
  {
    type: "error",
    name: "ERC20InsufficientAllowance",
    inputs: [
      { name: "spender",   type: "address", internalType: "address" },
      { name: "allowance", type: "uint256", internalType: "uint256" },
      { name: "needed",    type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InsufficientBalance",
    inputs: [
      { name: "sender",  type: "address", internalType: "address" },
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed",  type: "uint256", internalType: "uint256" },
    ],
  },
] as const;
